"""create table

Revision ID: 584eca54c2d4
Revises: 
Create Date: 2022-12-29 15:39:23.415453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584eca54c2d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
